### ISSUE TITLE
RNN 계열 Init

### ISSUE THREAD

**Issue by rainmaker712** [deeplearningzerotoall/TensorFlow#1]
@aisolab

**Comment by rainmaker712** [comment]
RNN은 보섭님과 함께 진행한다.

0. Basics (보섭)
- lab-12-0-rnn_basics
1. many to one (보섭)
- variable input sequence length (기존 char seq rnn example을 적당히 변경)
2. many to many (보섭)
- fixed input sequence length (기존 hello rnn example, language model이므로)
- variable input sequence length (품사태거 example 정도 쓰면 좋을 듯)
3. seq2seq
- variable input sequence length, variable output sequence length (simple nmt 만듬)
4. seq2seq with attention
- variable input sequence length, variable output sequence length (edited)

+ 기존의 내용을 gru/lstm or bidirectional로 내용을 추가

**Comment by seopbo** [comment]
오오 issue로 써놓으면 되겟네요 ㅋㅋ
