### ISSUE TITLE
[코드 중복] 같은 내용

### ISSUE THREAD

**Issue by simonjisu** [deeplearningzerotoall/TensorFlow#10]
1. [lab-02-1-Simple-Liner-Regression-eager.ipynb](https://github.com/deeplearningzerotoall/TensorFlow/blob/master/lab-02-1-Simple-Liner-Regression-eager.ipynb)
2. [lab-02-1-Simple_Liner_Regression-eager.ipynb](https://github.com/deeplearningzerotoall/TensorFlow/blob/master/lab-02-1-Simple_Liner_Regression-eager.ipynb)

승준님, 두 개가 같은 내용인데 중복 된것 같습니다. 전자에만 마지막에 "전체코드" 란이 있는데요. 혹시 괜찮으시면 2번째 파일 삭제해도 될까요?

**Comment by FinanceData** [comment]
예, 이름 바꾸는 과정에서 잘못 들어갔네요. 삭제 하시면 되겠습니다. 리뷰 감사합니다. 

이승준 드림

2019. 3. 5. 오후 2:33, Soo <notifications@github.com> 작성:
