### ISSUE TITLE
[Code] Convert .py to .ipynb + video numbering

### ISSUE THREAD

**Issue by simonjisu** [deeplearningzerotoall/TensorFlow#11]
준호님, 작성하신 코드 주피터 노트북으로 만들어 주실수 있을까요? 
Python 을 쓰면 간결하긴 한데, 처음 학습하시는 분들에게 주피터가 좋을 것 같습니다. 

추가로 영상 번호를 아래와 같이 할 예정이라, 코드 번호를 조금 수정해야할 것 같아요. 동영상은 앞부분만 바꿔서 갈아 낄수 있으면 부탁드리겠습니다. 
```
Lab 10-1: ReLU
Lab 10-2: Weight Init
Lab 10-3: Dropout
Lab 10-4: Batch Normalization
```

```
# relu part
lab-10-1 > lab 10-1-1 mnist_nn_softmax
lab-10-2 > lab 10-1-2 mnist_nn_relu

# weight init part
lab-10-3 > lab 10-2-1 mnist_nn_xavier
lab-10-4 > lab 10-2-2 mnist_nn_deep
# lab-10-4, 이 파일은 부연설명이 더 필요할 것 같습니다. 
# (뉴런갯수와 층을 조금 추가한거지만, 영상에는 나오지 않는 것이라서 간단하게 어떤 것을 했는지만 코드에 쓰면 될것 같아요) 

# dropout 
lab-10-5 > lab-10-3 mnist_nn_dropout

# batchnorm
lab-10-6 > lab-10-4 mnist_nn_batchnorm
```

**Comment by simonjisu** [comment]
추가로 궁금한것은 성킴님 이론 영상은 안쓰시는거죠? 지금 영상순서가 흐름이 좋은것 같아서요 ㅎㅎ 여쭤봅니당

**Comment by taki0112** [comment]
1. 영상.. 어떻게 편집하죠... ㅠㅠ... 그것만 알려주면... 앞부분만 짤라서 하도록 하겠습니다.. 맥인데.. imovie이걸로 하는건가요 ..?

2. 쥬피터가 익숙치 않긴한데,, 배워서 업로드 하도록 하겠습니다 ㅎㅎ

3. 성킴님 이론 영상은 사용하지 않습니다.

4. deep 파일은 주석으로 따로 작성하도록 할게요 ~

**Comment by simonjisu** [comment]
1. 그러면 일단 앞부분만 번호를 다시 매겨서 재 촬영만 해주실래요? ㅎㅎ 편집하시진 마시고
2. 추가로 지금 session 버젼을 밖으로 꺼내셨는데, 주피터 노트북을 만드시면서 eager 버젼을 밖으로 꺼내주시면 감사하겠습니당 ㅎㅎ

**Comment by taki0112** [comment]
모두 수정했습니다 ~

**Comment by simonjisu** [comment]
넵 감사합니다~
