### ISSUE TITLE
docker run -i -t 명령어 실행시 문제점

### ISSUE THREAD

**Issue by scholarchoi** [deeplearningzerotoall/TensorFlow#16]
하기 명령어를 실행하면, workspace 위치에서 명령어를 입력할 수 있도록 나오는게 아니라...
Jupytor Notebook 서버가 바로 실행이 된 상태가 됩니다.

docker run -i -t --name tf -p 8888:8888 -p 6006:6006 deeplearningzerotoall/tensorflow

workspace 위치에서 prompt가 깜빡이는 상태가 되어야, git clone 등의 명령어를 실행할 수가 있을텐데요.

바로 Jupytor Notebook 서버가 실행이 된 상태가 되다보니, ctrl + c 를 입력해도 Jupytor Notebook 서버가 종료되면서 바로 container가 종료되는 형태로 동작이 이뤄져서...

생성 및 실행된 tf 컨테이너에서 git clone 또는 pip install 명령을 실행해 볼 수가 없네요; (ㅜ.ㅜ)

혹시 저만 이런 문제를 겪고 있는 것인가요?

상기와 같은 문제로 인해서 Docker 튜토리얼을 제대로 따라갈 수가 없습니다; (ㅜ.ㅜ)

**Comment by iamjinn** [comment]
docker run -i -t --name tf -p 8888:8888 -p 6006:6006 deeplearningzerotoall/tensorflow 의 맨뒤에 bash 를 추가해 보세요.

즉, docker run -i -t --name tf -p 8888:8888 -p 6006:6006 deeplearningzerotoall/tensorflow bash 실행

**Comment by scholarchoi** [comment]
bash 를 붙이니깐 해결 되었네요~
감사합니다! (^^)
